---

- name: Fail if input configurations (server_configs) is not defined, skipping the task otherwise
  fail:
    msg: "server_configs is not defined" 
  when: server_configs is not defined

- name: Validating the server configs
  infn_cfg_validator:
    what_is_being_validated: "NTP Server Configurations - server_configs"
    configs: "{{ server_configs }}"
    schema: "{{ lookup('file', 'ntp_config_schema.json') | from_json | string }}"
  register: validation_res
  changed_when: false
  failed_when: not validation_res.validated