---
# NTP server configuration .
# Maximum of three NTP servers(NTP-1,NTP-2,NTP-3) are allowed to be configured for a given Network Element.
# Below is the sample template to configure the NTP servers for a given Network Element.
# IPv4 and IPv6 addresses are supported.
server_configs:
  server1:
    identifier       : NTP-1
    ipaddress        : 10.100.18.111

  # server2:
  #   identifier       : NTP-2
  #   ipaddress        : 2001:0db8:85a3:0000:0000:8a2e:0370:7334 #ip v6

  # server3:
  #   identifier       : NTP-3
  #   ipaddress        : 0.0.0.3

# NTP server state configuration template.
# This configuration is used for changing the state of the NTP server 
# Supported states are lock,unlock and maintenance 
state_configs:
  identifiers:
    - NTP-1
    - NTP-2
    - NTP-3

# NTP server alarm reporting configuration.
# This configuration is used for changing the alarm reporting setting 
# use this for enabling/ disabling alarm reporting
alarm_configs:
  identifiers:
    - NTP-1
    - NTP-2
    - NTP-3