---

###################################################################
#     Configurations for the tasks in the ne_call_home role       #
#       Refer the README for more details on the variables        #
#                                                                 #
# Sub Sections in the configuration:                              #
# - configure - Required for the configure task                   #
# - delete - Required for the delete task                         #
# - invoke - Required for the invoke task                         #
###################################################################
ne_call_home_configs:
##############################################################################################################################################
  # The list of configurations that are to be edited or created.
  # In case they are present on the Network Element then the existing ones will be edited.
  # In case they are not present on the Network Element then new ones with the input will be created.
  # The value of protocol is case sensitive - SSH/TLS and not ssh/tls.
  configure:
    - identifier: CallHomeIdentifier1
      dest_address: 10.220.15.39
      timeout: 25
      retry_count: 4

    - identifier: CallHomeIdentifier2
      dest_address: 10.220.5.39
      dest_port: 9090
      retry_count: 4
      timeout: 12
      protocol: SSH # Case sensitive - SSH/TLS and not ssh/tls

    - identifier: CallHomeIdentifier3
      dest_address: 10.220.165.87
      dest_port: 5432
      retry_count: 2
      timeout: 15
      protocol: SSH # Case sensitive - SSH/TLS and not ssh/tls
##############################################################################################################################################
  # The list of identifiers, each of which corresponds to a Call Home Setting on the Network Element, that are going to be deleted.
  delete:
    - CallHomeIdentifier1
    - CallHomeIdentifier2
    - CallHomeIdentifier3

##############################################################################################################################################
  # The list of identifiers, each of which corresponds to a Call Home Setting on the Network Element, 
  # that are going to be used for invoking an on demand Call Home Session.
  invoke:
    - CallHomeIdentifier1
    - CallHomeIdentifier2
    - CallHomeIdentifier3
