sw_mapper:
  "FILE": "file_name"
  "CRDAT": "create_date"
  "CRTIME": "create_time"
  "FILETYPE": "file_format"
  "FORMAT": "format"
  "METARHASH": "meta_hash"
  "SIZE": "size"
  "SWVERSION": "sw_version"
  "USAGE": "usage"
  "VALIDITY": "validity"
  "ACLISESSION": "acli_session"
  "AUTHPOLICY": "auth_policy"
  "DURAL": "lockout_duration"
  "FXFRSSH": "is_ssh_enabled"
  "HTTPS": "is_https_enabled"
  "MAXSESS": "max_no_sessions"
  "MXINV": "max_invalid_login_allowed"
  "PIDCHGPOLICY": "passwd_change_policy"
  "POSTLOGINWARNDIS": "is_post_login_warning"
  "PRELOGINWARNDIS": "is_pre_login_warning"
  "PWDDIGEST": "password_digest"
  "PWDROT": "password_rotation"
  "SCP": "is_scp_enabled"
  "SECUREALL": "secure_mode_all"
  "SERIALACCESS": "serial_port_access"
  "SSHFINGERPRINT": "ssh_fingerprint"
  "TL1SSH": "is_tl1_ssh_enabled"
  "TLSCERT": "tls_certificate"
  "TLSCONNTIME": "tls_conn_time"
  "TLSIDLETIME": "tls_idle_time"
  "TNETSSH": "is_telenet_ssh_enabled"
  "XMLSSH": "is_xml_enabled"
  "CURRXFRPROGRESS":  "current_xfr_progress"
  "CURRXFRSTATE":  "current_xfr_state"
  "FTPFILETYPE":  "ftp_file_type"
  "FTPTRANSFER":  "ftp_transfer"
  "LASTATTEMPTXFRDATE":  "last_attempt_xfr_date"
  "LASTATTEMPTXFRTIME":  "last_attempt_xfr_time"
  "LASTSUCCXFRDATE":  "last_success_xfr_date"
  "LASTSUCCXFRFILE":  "last_success_xfr_file"
  "LASTSUCCXFRIP":  "last_success_xfr_ip"
  "LASTSUCCXFRTIME":  "last_success_xfr_time"
  "LASTXFRSTATE_PRI":  "last_xfr_state_pri"
  "LASTXFRSTATE_SEC":  "last_xfr_state_sec"
  "PRIDSTFILENAME":  "primary_dst_file_name"
  "PRIDSTFILEPATH":  "primary_dst_file_path"
  "PRIFTPIP":  "primary_ftp_ip"
  "PRIFTPUID":  "primary_ftp_uid"
  "SECFTPIP":  "secondary_ftp_ip"
  "SECFTPUID":  "secondary_ftp_uid"
  "SFTPPRIPORT":  "sftp_primary_port"
  "SFTPSECPORT":  "sftp_secondary_port"

system_information_mapper:
    LABEL: label
    CLLI: common_language_location_identifier
    NENAME: ne_name
    NETYPE: ne_type
    BPIPADDR: backplane_ip_address
    NODEID: node_id
    LOCATION1: location1
    LOCATION2: location2
    LATITUDE: latitude_in_degrees
    LONGITUDE: longitude_in_degrees
    SYSDATE: system_date_in_YYYY-MM-DD
    SYSTIME: system_time_in_HH-MM-SS
    SYSACTIVEDATE: system_active_date_in_YYYY-MM-DD
    SYSACTIVETIME: system_active_time_in_HH-MM-SS
    TIMEZONEOFFSET: time_zone_offset
    DBVERS: database_version
    SWVERSION: software_version
    ROUTERID: router_id_ip_address
    DCNIP: dcn_ipv4_address
    DCNIPNETMASK: dcn_ipv4_subnet_mask
    DCNIP6: dcn_ipv6_address
    DCNIP6NETMASK: dcn_ipv6_subnet_mask
    CRAFTIP: craft_ip_address
    CRAFTIPNETMASK: craft_ipv4_subnet_mask
    CRAFTIP6: craft_ipv6_address
    CRAFTIP6NETMASK: craft_ipv6_subnet_mask
    DCNIP6LINKLOCAL: dcn_link_local_ipv6_address
    GNE: is_gne_enabled
    TL1PORT: tl1_port
    XMLPORT: xml_port
    AUXIP: aux_ip_address
    AUXMASK: aux_ip_netmask
    PRIMGNEADDR: primary_gne_ip_address
    SECGNEADDR: secondary_gne_ip_address
    DCNDEST: dcn_dest_ipv4_address
    DCNGTWY: dcn_gateway_ipv4_address
    DCNDESTPREFIXLEN: dcn_ipv4_dest_prefix_length
    DCNGLOBALROUTE: dcn_global_route
    DCNDEST6: dcn_ipv6_dest
    DCNGTWY6: dcn_ipv6_gateway
    DCNDEST6PREFIXLEN: dcn_dest_ipv6_prefix_length
    SWBUILDINFO: software_build_information
    XMLPROXYPORT: xml_proxy_port
    FTPPROXYPORT: ftp_proxy_port
    TNETPROXYPORT: telnet_proxy_port
    HTTPPROXYPORT: http_proxy_port
    DETCHASSISLIST: detected_and_unprovisioned_chasiss_list
    AVAILABLEPERSISTENTSPACE: available_persistent_space_in_bytes
    TOTALPERSISTENTSPACE: total_persistent_space_in_bytes
    SYSRESETNEEDED: system_reset_needed
    ARCCTRL: alarm_reporting_control
    AUXTOSCHG: aux_port_type_of_service_change
    AUXIFRATE: aux_ip_interface_rate_in_Mbps
    AUXIFSTATUS: aux_ip_interface_admin_state
    CRAFTIFSTATUS: craft_ip_interface_admin_state
    OSCOOBENABLE: is_out_of_band_osc_enabled
    TLPBKCTRL: terminal_loopback_control
    LASTUPGRADEDATE: last_upgrade_date
    LASTUPGRADETIME: last_upgrade_time
    RESTHOLDOFFTIMER0: hold_of_timer_for_restore_priority_level_0
    RESTHOLDOFFTIMER1: hold_of_timer_for_restore_priority_level_1
    RESTHOLDOFFTIMER2: hold_of_timer_for_restore_priority_level_2
    RESTHOLDOFFTIMER3: hold_of_timer_for_restore_priority_level_3
    RESTHOLDOFFTIMER4: hold_of_timer_for_restore_priority_level_4
    RESTHOLDOFFTIMER5: hold_of_timer_for_restore_priority_level_5
    RESTHOLDOFFTIMER6: hold_of_timer_for_restore_priority_level_6
    RESTHOLDOFFTIMER7: hold_of_timer_for_restore_priority_level_7
    ENHPROTSW: is_enhanced_protection_switching_enabled
    ALSADMINPOLICY: als_administration_policy
    NCSHELFID: node_controller_shelf_id
    MIGRATESTAT: expansion_chassis_migrate_status
    DCNIFADSTAT: is_dcn_interface_enabled
    LASTPREPUPGRADEDATE: last_prepare_upgrade_date
    LASTPREPUPGRADETIME: last_prepare_upgrade_time
    PREPUPGRADESUCCESSDATE: prepare_upgrade_last_success_date
    PREPUPGRADESUCCESSTIME: prepare_upgrade_success_time
    UPGRADESTAT: node_upgrade_status
    SYSLOG: is_syslog_enabled
    DCNROUTETYPE: dcn_ipv4_route_type
    DCNROUTECOST: dcn_ipv4_route_cost
    DCN6ROUTETYPE: dcn_ipv6_route_type
    DCN6ROUTECOST: dcn_ipv6_route_cost
    DBENCKEY: CSP_encryption_key_in_mode1
    DBBACKUPMODE: database_backup_mode
    SAMPLEINTERVAL: pm_reporting_time_interval_in_ms
    GRPC: is_grpc_enabled
    SITEID: configured_site_identifier
    HEARTBEATINTERVAL: heartbeat_interval
