---

- name: Retrieving the Call Home Settings
  infn_tl1:
    provider: "{{ tl1 }}"
    commands_and_inputs: "{{ lookup('template', 'retrieve.j2') }}"
    output: "json"
    save: "{{ module_save_file | default('infn_tl1') }}.txt"
  register: rtrv_ne_call_home_res
  changed_when: false
  failed_when: rtrv_ne_call_home_res.status == "FAILURE"

- name: Renaming Raw Response Parameters
  infn_mapper:
    mapper: "{{ ne_call_home_mapper }}"
    tl1_response: "{{ rtrv_ne_call_home_res }}"
  register: mapped_rtrv_ne_call_home_res
  when:
    - ne_call_home_mapper is defined

- name: Result of the Retrieval
  debug:
    msg: "{%- if mapped_rtrv_ne_call_home_res.skipped | default(false) -%}{{- rtrv_ne_call_home_res -}}{%- else -%}{{- mapped_rtrv_ne_call_home_res -}}{%- endif -%}"
