---

- name: Retrieving Database Image(s) Information
  infn_tl1:
    provider: "{{ tl1 }}"
    commands_and_inputs: "{{ lookup('template', 'retrieve_db.j2') }}"
    output: "json"
    save: "{{ module_save_file | default('infn_tl1') }}.txt"
  register: rtrv_db_info_res
  changed_when: false
  failed_when: rtrv_db_info_res.status == 'FAILURE'
  
- name: Getting Current Image(s) Names
  set_fact:
    current_db_name: "{{ lookup('template', 'current_db_name.j2') }}"