---

- name: Software Upgrade
  block:
    
    - name: Retrieving Software file Information
      include_tasks: retrieve_sw_info.yml

    - name: Fail if SW image is not present for Upgrade, Skip the task otherwise
      fail: 
        msg: "SW Image not present for Upgrade"
      when: non_current_sw_version == ''
    
    - name: Saving current SW Image version for validating upgarde 
      set_fact:
        prerun_current_sw_version: "{{ current_sw_version }}"

    - name: Initiating the Software Upgrade
      infn_tl1:
        provider: "{{ tl1 }}"
        commands_and_inputs: "{{ lookup('template', 'upgrade.j2') }}"
        output: "json"
        save: "{{ module_save_file | default('infn_tl1') }}.txt"
      register: init_sw_up_res
      changed_when: init_sw_up_res.status == 'SUCCESS'
      failed_when: init_sw_up_res.status == 'FAILURE'
      
    - name: "Pausing for {{ sw_configs.upgrade_wait_time | default(upgrade_wait_time) }} minute(s)"
      pause:
        minutes: "{{ sw_configs.upgrade_wait_time | default(upgrade_wait_time) }}"

    - name: Checking if the Network Element is reachable
      include_tasks: availability.yml

    - name: Check if Software Upgrade is successful
      include_tasks: check_upgrade.yml

    - name: Summary of the Task
      debug:
        msg: "{{ init_sw_up_res }}"
