---

# Requires ansible 1.8+
- hosts: "{{ host_group }}"
  connection: local
  gather_facts: False
  vars_prompt:
    - name: new_password
      prompt: "Type your new password"
    
  vars:
    NE_IP: "{{ ne_ip | default(hostvars[inventory_hostname]['ansible_host']) }}"
    NE_User: "secadmin"
    NE_Pwd: "passwd"
    TID: "{{ hostvars[inventory_hostname]['tid'] | default('') }}"

  tasks:

    - import_role:
        name: security
      vars:
        task_name: change_passwd
      tags: change_passwd

    - set_fact: 
        NE_Pwd: "{{ new_password }}"
        
    - import_role:
        name: security
      vars:
        task_name: enable_user
      tags: enable_user
    